server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: zyy
    password: 707431829mz
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    password: 123456
    timeout: 10000

logging:
  config: classpath:log4j2.xml